[package]
name = "Zion-Cross-Chain"
version = "2.0.1"

[addresses]
StarcoinFramework = "0x1"
Bridge = "0xf8ea2d94b8a7d83ace33bb56731268e0"

[dependencies]
# v1.12.9
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "c101e26a45401671ae04b5571387661f0fc3656f" }
#Bridge-STC-SMT = { local = "../stc-smt" }
Bridge-STC-Utils = { local = "../stc-utils" }
#Bridge-STC-Assets = { local = "../stc-assets" }